services:

  mysql:
    image: mysql:8
    container_name: mysql-simohu
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql 

  redis:
    image: "redis:latest"
    container_name: redis-simohu
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data